# curl --location --request GET 'http://localhost:3000/api/vessel'
#--header 'x-api-key: shippo'
#--header 'Cookie: __profilin=p%3Dt'
GET http://localhost:3000/api/vessel
x-api-key: shippo
Cookie: __profilin=p%3Dt

###

