# curl --location --request POST 'http://localhost:3000/api/vessel'
#--header 'x-api-key: shippo'
#--form 'name="sudhan"'
#--form 'owner_id="12"'
#--form 'naccs_code="1202"'
POST http://localhost:3000/api/vessel
x-api-key: shippo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

"sudhan"
--WebAppBoundary
Content-Disposition: form-data; name="owner_id"

"12"
--WebAppBoundary
Content-Disposition: form-data; name="naccs_code"

"120A2"
--WebAppBoundary--

###

